% %Create a linearArray with dipole element.
% Generated by MATLAB(R) 9.7 and Antenna Toolbox 4.1.
% Generated on: 05-Oct-2021 11:20:13

%% Array Properties 
%Define Array
arrayObject = linearArray;

arrayObject.NumElements = 6;

%Define Array Elements
Element1 = dipole;
arrayObject.Element = [Element1 ];

% Design array at frequency 300000000Hz
arrayObject = design(arrayObject,300000000,Element1);
%arrayObject Properties Changed
arrayObject.ElementSpacing = 0.5;


%% Array Analysis 
% Show for linearArray
figure;
show(arrayObject) 
% Layout for linearArray
figure;
layout(arrayObject) 

