% %Create a linearArray with dipole element.
% Generated by MATLAB(R) 9.7 and Antenna Toolbox 4.1.
% Generated on: 06-Oct-2021 10:05:24

%% Array Properties 
%Define Array
arrayObject = linearArray;

arrayObject.NumElements = 6;

%Define Array Elements
Element1 = dipole;
arrayObject.Element = [Element1 ];

%arrayObject Properties Changed
arrayObject.ElementSpacing = 0.17;

%Element1 Properties Changed
arrayObject.Element(1).Length = 0.5;
arrayObject.Element(1).Width = 0.001;

%% Array Analysis 
% Show for linearArray
figure;
show(arrayObject) 
% Layout for linearArray
figure;
layout(arrayObject) 
% Pattern for linearArray
plotFrequency = 3000000000; Termination = 50;
figure;
pattern(arrayObject, plotFrequency,'Termination',Termination); 
% Azimuth for linearArray
plotFrequency = 3000000000; azRange = 0:5:360; Termination = 50;
figure;
pattern(arrayObject, plotFrequency,azRange,0,'Termination',Termination);

